# Generated by Django 4.2.3 on 2023-08-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('presentacion', models.TextField()),
                ('experiencia', models.TextField()),
                ('estudios', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=50)),
                ('nombreEmpresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('detalles', models.TextField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('sueldo', models.IntegerField(max_length=50)),
            ],
        ),
    ]
